### PR TITLE
added font-stretch property

### PR DESCRIPTION
**Pull request by nico-martin**
Added the font-stretch as a possible option/css-property

### CODE REVIEW

**Comment by jalkoby** [comment]
please fix tests as well

**Comment by nico-martin** [comment]
I added my changes to the test file. But it still failes. The thing is I don't think the fail is caused by my changes, but by some older changes: https://travis-ci.org/jalkoby/gulp-inline-fonts/builds/338012371
Could you have a look at this?

**Comment by nico-martin** [comment]
Ifixed the other tests as well. But then, the node 4 timed out: https://travis-ci.org/jalkoby/gulp-inline-fonts/builds/403514421?utm_source=github_status&utm_medium=notification
So I removed that and now all checks have passed.

**Comment by jalkoby** [comment]
Perfect, will release in a few hours

**Comment by jalkoby** [comment]
welcome v1.1.0

**Pull request merged**
