### PR TITLE
Fixes for file path that contains multiple dots

### PR DESCRIPTION
**Pull request by anagorsky**
Example case:
../a.b.c/SansPro.otf

Thanks & Regards
Vitaly

### CODE REVIEW

**Comment by jalkoby** [comment]
@anagorsky thank you for your effort, but the change has broken the tests. Please, fix them and I'll merge the pull request

**Comment by anagorsky** [comment]
@jalkoby 
The popular [mime](https://github.com/broofa/node-mime) library based on [mime-db](https://github.com/jshttp/mime-db) determine "ttf" extension as "x-font-ttf" type that is not equal to the compare value on the second case of the tests which is "x-font-truetype". So to skip test, I just replaced types.

**Comment by jalkoby** [comment]
@anagorsky sorry, forgot to tell you to squash the commits. Please, squash the commits, there is no need for 2 small commit

**Comment by jalkoby** [comment]
looks like Github has a squashing mechanism out-of-box, so I did it by myself. Thank @anagorsky  for the contribution

**Pull request merged**
